#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendas.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_sistema")]
	public partial class VendasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_categoria(tb_categoria instance);
    partial void Updatetb_categoria(tb_categoria instance);
    partial void Deletetb_categoria(tb_categoria instance);
    partial void Inserttb_contas_receber(tb_contas_receber instance);
    partial void Updatetb_contas_receber(tb_contas_receber instance);
    partial void Deletetb_contas_receber(tb_contas_receber instance);
    partial void Inserttb_itens_venda(tb_itens_venda instance);
    partial void Updatetb_itens_venda(tb_itens_venda instance);
    partial void Deletetb_itens_venda(tb_itens_venda instance);
    partial void Inserttb_pessoa(tb_pessoa instance);
    partial void Updatetb_pessoa(tb_pessoa instance);
    partial void Deletetb_pessoa(tb_pessoa instance);
    partial void Inserttb_produto(tb_produto instance);
    partial void Updatetb_produto(tb_produto instance);
    partial void Deletetb_produto(tb_produto instance);
    partial void Inserttb_status(tb_status instance);
    partial void Updatetb_status(tb_status instance);
    partial void Deletetb_status(tb_status instance);
    partial void Inserttb_usuario(tb_usuario instance);
    partial void Updatetb_usuario(tb_usuario instance);
    partial void Deletetb_usuario(tb_usuario instance);
    partial void Inserttb_venda(tb_venda instance);
    partial void Updatetb_venda(tb_venda instance);
    partial void Deletetb_venda(tb_venda instance);
    #endregion
		
		public VendasDataContext() : 
				base(global::Vendas.DAL.Properties.Settings.Default.db_sistemaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VendasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VendasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VendasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VendasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_categoria> tb_categorias
		{
			get
			{
				return this.GetTable<tb_categoria>();
			}
		}
		
		public System.Data.Linq.Table<tb_contas_receber> tb_contas_recebers
		{
			get
			{
				return this.GetTable<tb_contas_receber>();
			}
		}
		
		public System.Data.Linq.Table<tb_itens_venda> tb_itens_vendas
		{
			get
			{
				return this.GetTable<tb_itens_venda>();
			}
		}
		
		public System.Data.Linq.Table<tb_pessoa> tb_pessoas
		{
			get
			{
				return this.GetTable<tb_pessoa>();
			}
		}
		
		public System.Data.Linq.Table<tb_produto> tb_produtos
		{
			get
			{
				return this.GetTable<tb_produto>();
			}
		}
		
		public System.Data.Linq.Table<tb_status> tb_status
		{
			get
			{
				return this.GetTable<tb_status>();
			}
		}
		
		public System.Data.Linq.Table<tb_usuario> tb_usuarios
		{
			get
			{
				return this.GetTable<tb_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tb_venda> tb_vendas
		{
			get
			{
				return this.GetTable<tb_venda>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoria")]
	public partial class tb_categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _desc_categoria;
		
		private EntitySet<tb_produto> _tb_produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void Ondesc_categoriaChanging(string value);
    partial void Ondesc_categoriaChanged();
    #endregion
		
		public tb_categoria()
		{
			this._tb_produtos = new EntitySet<tb_produto>(new Action<tb_produto>(this.attach_tb_produtos), new Action<tb_produto>(this.detach_tb_produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_categoria", DbType="NVarChar(50)")]
		public string desc_categoria
		{
			get
			{
				return this._desc_categoria;
			}
			set
			{
				if ((this._desc_categoria != value))
				{
					this.Ondesc_categoriaChanging(value);
					this.SendPropertyChanging();
					this._desc_categoria = value;
					this.SendPropertyChanged("desc_categoria");
					this.Ondesc_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_produto", Storage="_tb_produtos", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<tb_produto> tb_produtos
		{
			get
			{
				return this._tb_produtos;
			}
			set
			{
				this._tb_produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_produtos(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_categoria = this;
		}
		
		private void detach_tb_produtos(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_contas_receber")]
	public partial class tb_contas_receber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_conta;
		
		private System.Nullable<System.DateTime> _data_compra;
		
		private System.Nullable<System.DateTime> _data_vencimento;
		
		private System.Nullable<System.DateTime> _data_pagamento;
		
		private System.Nullable<int> _id_status;
		
		private System.Nullable<int> _id_venda;
		
		private EntityRef<tb_status> _tb_status;
		
		private EntityRef<tb_venda> _tb_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_contaChanging(int value);
    partial void Onid_contaChanged();
    partial void Ondata_compraChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_compraChanged();
    partial void Ondata_vencimentoChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_vencimentoChanged();
    partial void Ondata_pagamentoChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_pagamentoChanged();
    partial void Onid_statusChanging(System.Nullable<int> value);
    partial void Onid_statusChanged();
    partial void Onid_vendaChanging(System.Nullable<int> value);
    partial void Onid_vendaChanged();
    #endregion
		
		public tb_contas_receber()
		{
			this._tb_status = default(EntityRef<tb_status>);
			this._tb_venda = default(EntityRef<tb_venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_conta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_conta
		{
			get
			{
				return this._id_conta;
			}
			set
			{
				if ((this._id_conta != value))
				{
					this.Onid_contaChanging(value);
					this.SendPropertyChanging();
					this._id_conta = value;
					this.SendPropertyChanged("id_conta");
					this.Onid_contaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_compra", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_compra
		{
			get
			{
				return this._data_compra;
			}
			set
			{
				if ((this._data_compra != value))
				{
					this.Ondata_compraChanging(value);
					this.SendPropertyChanging();
					this._data_compra = value;
					this.SendPropertyChanged("data_compra");
					this.Ondata_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_vencimento", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_vencimento
		{
			get
			{
				return this._data_vencimento;
			}
			set
			{
				if ((this._data_vencimento != value))
				{
					this.Ondata_vencimentoChanging(value);
					this.SendPropertyChanging();
					this._data_vencimento = value;
					this.SendPropertyChanged("data_vencimento");
					this.Ondata_vencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_pagamento", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_pagamento
		{
			get
			{
				return this._data_pagamento;
			}
			set
			{
				if ((this._data_pagamento != value))
				{
					this.Ondata_pagamentoChanging(value);
					this.SendPropertyChanging();
					this._data_pagamento = value;
					this.SendPropertyChanged("data_pagamento");
					this.Ondata_pagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int")]
		public System.Nullable<int> id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					if (this._tb_status.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", DbType="Int")]
		public System.Nullable<int> id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					if (this._tb_venda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_tb_contas_receber", Storage="_tb_status", ThisKey="id_status", OtherKey="id_status", IsForeignKey=true)]
		public tb_status tb_status
		{
			get
			{
				return this._tb_status.Entity;
			}
			set
			{
				tb_status previousValue = this._tb_status.Entity;
				if (((previousValue != value) 
							|| (this._tb_status.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_status.Entity = null;
						previousValue.tb_contas_recebers.Remove(this);
					}
					this._tb_status.Entity = value;
					if ((value != null))
					{
						value.tb_contas_recebers.Add(this);
						this._id_status = value.id_status;
					}
					else
					{
						this._id_status = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_status");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_contas_receber", Storage="_tb_venda", ThisKey="id_venda", OtherKey="id_venda", IsForeignKey=true)]
		public tb_venda tb_venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				tb_venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.tb_contas_recebers.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.tb_contas_recebers.Add(this);
						this._id_venda = value.id_venda;
					}
					else
					{
						this._id_venda = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itens_venda")]
	public partial class tb_itens_venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _quantidade;
		
		private int _id_produto;
		
		private int _id_venda;
		
		private decimal _valor;
		
		private int _id_item;
		
		private EntityRef<tb_produto> _tb_produto;
		
		private EntityRef<tb_venda> _tb_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnquantidadeChanging(int value);
    partial void OnquantidadeChanged();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void OnvalorChanging(decimal value);
    partial void OnvalorChanged();
    partial void Onid_itemChanging(int value);
    partial void Onid_itemChanged();
    #endregion
		
		public tb_itens_venda()
		{
			this._tb_produto = default(EntityRef<tb_produto>);
			this._tb_venda = default(EntityRef<tb_venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Int NOT NULL")]
		public int quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", DbType="Int NOT NULL")]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					if (this._tb_produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", DbType="Int NOT NULL")]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					if (this._tb_venda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2) NOT NULL")]
		public decimal valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_item
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.Onid_itemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("id_item");
					this.Onid_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_itens_venda", Storage="_tb_produto", ThisKey="id_produto", OtherKey="id_produto", IsForeignKey=true)]
		public tb_produto tb_produto
		{
			get
			{
				return this._tb_produto.Entity;
			}
			set
			{
				tb_produto previousValue = this._tb_produto.Entity;
				if (((previousValue != value) 
							|| (this._tb_produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_produto.Entity = null;
						previousValue.tb_itens_vendas.Remove(this);
					}
					this._tb_produto.Entity = value;
					if ((value != null))
					{
						value.tb_itens_vendas.Add(this);
						this._id_produto = value.id_produto;
					}
					else
					{
						this._id_produto = default(int);
					}
					this.SendPropertyChanged("tb_produto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itens_venda", Storage="_tb_venda", ThisKey="id_venda", OtherKey="id_venda", IsForeignKey=true)]
		public tb_venda tb_venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				tb_venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.tb_itens_vendas.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.tb_itens_vendas.Add(this);
						this._id_venda = value.id_venda;
					}
					else
					{
						this._id_venda = default(int);
					}
					this.SendPropertyChanged("tb_venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoas")]
	public partial class tb_pessoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pessoa;
		
		private string _desc_pessoa;
		
		private EntityRef<tb_usuario> _tb_usuario;
		
		private EntitySet<tb_venda> _tb_vendas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pessoaChanging(int value);
    partial void Onid_pessoaChanged();
    partial void Ondesc_pessoaChanging(string value);
    partial void Ondesc_pessoaChanged();
    #endregion
		
		public tb_pessoa()
		{
			this._tb_usuario = default(EntityRef<tb_usuario>);
			this._tb_vendas = new EntitySet<tb_venda>(new Action<tb_venda>(this.attach_tb_vendas), new Action<tb_venda>(this.detach_tb_vendas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_pessoa", DbType="NVarChar(50)")]
		public string desc_pessoa
		{
			get
			{
				return this._desc_pessoa;
			}
			set
			{
				if ((this._desc_pessoa != value))
				{
					this.Ondesc_pessoaChanging(value);
					this.SendPropertyChanging();
					this._desc_pessoa = value;
					this.SendPropertyChanged("desc_pessoa");
					this.Ondesc_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_usuario", Storage="_tb_usuario", ThisKey="id_pessoa", OtherKey="id_pessoa", IsUnique=true, IsForeignKey=false)]
		public tb_usuario tb_usuario
		{
			get
			{
				return this._tb_usuario.Entity;
			}
			set
			{
				tb_usuario previousValue = this._tb_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_usuario.Entity = null;
						previousValue.tb_pessoa = null;
					}
					this._tb_usuario.Entity = value;
					if ((value != null))
					{
						value.tb_pessoa = this;
					}
					this.SendPropertyChanged("tb_usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_venda", Storage="_tb_vendas", ThisKey="id_pessoa", OtherKey="id_pessoa")]
		public EntitySet<tb_venda> tb_vendas
		{
			get
			{
				return this._tb_vendas;
			}
			set
			{
				this._tb_vendas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_vendas(tb_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_pessoa = this;
		}
		
		private void detach_tb_vendas(tb_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_pessoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produto")]
	public partial class tb_produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_produto;
		
		private string _desc_produto;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<int> _id_categoria;
		
		private EntitySet<tb_itens_venda> _tb_itens_vendas;
		
		private EntityRef<tb_categoria> _tb_categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Ondesc_produtoChanging(string value);
    partial void Ondesc_produtoChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void Onid_categoriaChanging(System.Nullable<int> value);
    partial void Onid_categoriaChanged();
    #endregion
		
		public tb_produto()
		{
			this._tb_itens_vendas = new EntitySet<tb_itens_venda>(new Action<tb_itens_venda>(this.attach_tb_itens_vendas), new Action<tb_itens_venda>(this.detach_tb_itens_vendas));
			this._tb_categoria = default(EntityRef<tb_categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_produto", DbType="NVarChar(50)")]
		public string desc_produto
		{
			get
			{
				return this._desc_produto;
			}
			set
			{
				if ((this._desc_produto != value))
				{
					this.Ondesc_produtoChanging(value);
					this.SendPropertyChanging();
					this._desc_produto = value;
					this.SendPropertyChanged("desc_produto");
					this.Ondesc_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(25,2)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int")]
		public System.Nullable<int> id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._tb_categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_itens_venda", Storage="_tb_itens_vendas", ThisKey="id_produto", OtherKey="id_produto")]
		public EntitySet<tb_itens_venda> tb_itens_vendas
		{
			get
			{
				return this._tb_itens_vendas;
			}
			set
			{
				this._tb_itens_vendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_produto", Storage="_tb_categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public tb_categoria tb_categoria
		{
			get
			{
				return this._tb_categoria.Entity;
			}
			set
			{
				tb_categoria previousValue = this._tb_categoria.Entity;
				if (((previousValue != value) 
							|| (this._tb_categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_categoria.Entity = null;
						previousValue.tb_produtos.Remove(this);
					}
					this._tb_categoria.Entity = value;
					if ((value != null))
					{
						value.tb_produtos.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_itens_vendas(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = this;
		}
		
		private void detach_tb_itens_vendas(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_status")]
	public partial class tb_status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _status;
		
		private EntitySet<tb_contas_receber> _tb_contas_recebers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public tb_status()
		{
			this._tb_contas_recebers = new EntitySet<tb_contas_receber>(new Action<tb_contas_receber>(this.attach_tb_contas_recebers), new Action<tb_contas_receber>(this.detach_tb_contas_recebers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_tb_contas_receber", Storage="_tb_contas_recebers", ThisKey="id_status", OtherKey="id_status")]
		public EntitySet<tb_contas_receber> tb_contas_recebers
		{
			get
			{
				return this._tb_contas_recebers;
			}
			set
			{
				this._tb_contas_recebers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_contas_recebers(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_status = this;
		}
		
		private void detach_tb_contas_recebers(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_status = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_usuario")]
	public partial class tb_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _usuario;
		
		private string _senha;
		
		private int _id_pessoa;
		
		private EntityRef<tb_pessoa> _tb_pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void Onid_pessoaChanging(int value);
    partial void Onid_pessoaChanged();
    #endregion
		
		public tb_usuario()
		{
			this._tb_pessoa = default(EntityRef<tb_pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					if (this._tb_pessoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_usuario", Storage="_tb_pessoa", ThisKey="id_pessoa", OtherKey="id_pessoa", IsForeignKey=true)]
		public tb_pessoa tb_pessoa
		{
			get
			{
				return this._tb_pessoa.Entity;
			}
			set
			{
				tb_pessoa previousValue = this._tb_pessoa.Entity;
				if (((previousValue != value) 
							|| (this._tb_pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_pessoa.Entity = null;
						previousValue.tb_usuario = null;
					}
					this._tb_pessoa.Entity = value;
					if ((value != null))
					{
						value.tb_usuario = this;
						this._id_pessoa = value.id_pessoa;
					}
					else
					{
						this._id_pessoa = default(int);
					}
					this.SendPropertyChanged("tb_pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_venda")]
	public partial class tb_venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venda;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<decimal> _desconto;
		
		private System.Nullable<decimal> _valor_pago;
		
		private System.Nullable<int> _id_pessoa;
		
		private EntitySet<tb_contas_receber> _tb_contas_recebers;
		
		private EntitySet<tb_itens_venda> _tb_itens_vendas;
		
		private EntityRef<tb_pessoa> _tb_pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void OndescontoChanging(System.Nullable<decimal> value);
    partial void OndescontoChanged();
    partial void Onvalor_pagoChanging(System.Nullable<decimal> value);
    partial void Onvalor_pagoChanged();
    partial void Onid_pessoaChanging(System.Nullable<int> value);
    partial void Onid_pessoaChanged();
    #endregion
		
		public tb_venda()
		{
			this._tb_contas_recebers = new EntitySet<tb_contas_receber>(new Action<tb_contas_receber>(this.attach_tb_contas_recebers), new Action<tb_contas_receber>(this.detach_tb_contas_recebers));
			this._tb_itens_vendas = new EntitySet<tb_itens_venda>(new Action<tb_itens_venda>(this.attach_tb_itens_vendas), new Action<tb_itens_venda>(this.detach_tb_itens_vendas));
			this._tb_pessoa = default(EntityRef<tb_pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desconto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> desconto
		{
			get
			{
				return this._desconto;
			}
			set
			{
				if ((this._desconto != value))
				{
					this.OndescontoChanging(value);
					this.SendPropertyChanging();
					this._desconto = value;
					this.SendPropertyChanged("desconto");
					this.OndescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_pago", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor_pago
		{
			get
			{
				return this._valor_pago;
			}
			set
			{
				if ((this._valor_pago != value))
				{
					this.Onvalor_pagoChanging(value);
					this.SendPropertyChanging();
					this._valor_pago = value;
					this.SendPropertyChanged("valor_pago");
					this.Onvalor_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", DbType="Int")]
		public System.Nullable<int> id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					if (this._tb_pessoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_contas_receber", Storage="_tb_contas_recebers", ThisKey="id_venda", OtherKey="id_venda")]
		public EntitySet<tb_contas_receber> tb_contas_recebers
		{
			get
			{
				return this._tb_contas_recebers;
			}
			set
			{
				this._tb_contas_recebers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itens_venda", Storage="_tb_itens_vendas", ThisKey="id_venda", OtherKey="id_venda")]
		public EntitySet<tb_itens_venda> tb_itens_vendas
		{
			get
			{
				return this._tb_itens_vendas;
			}
			set
			{
				this._tb_itens_vendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_venda", Storage="_tb_pessoa", ThisKey="id_pessoa", OtherKey="id_pessoa", IsForeignKey=true)]
		public tb_pessoa tb_pessoa
		{
			get
			{
				return this._tb_pessoa.Entity;
			}
			set
			{
				tb_pessoa previousValue = this._tb_pessoa.Entity;
				if (((previousValue != value) 
							|| (this._tb_pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_pessoa.Entity = null;
						previousValue.tb_vendas.Remove(this);
					}
					this._tb_pessoa.Entity = value;
					if ((value != null))
					{
						value.tb_vendas.Add(this);
						this._id_pessoa = value.id_pessoa;
					}
					else
					{
						this._id_pessoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_contas_recebers(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = this;
		}
		
		private void detach_tb_contas_recebers(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = null;
		}
		
		private void attach_tb_itens_vendas(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = this;
		}
		
		private void detach_tb_itens_vendas(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = null;
		}
	}
}
#pragma warning restore 1591
